<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Censeq.FileManagement</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Domain" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Censeq.FileManagement.Domain.Shared\Censeq.FileManagement.Domain.Shared.csproj" />
  </ItemGroup>
</Project>
