<Project Sdk="Microsoft.NET.Sdk.Web">
	<Import Project="..\..\common.props" />

	<PropertyGroup>
		<IsPackable>true</IsPackable>
		<OutputType>Library</OutputType>
		<AssemblyName>Censeq.Framework.AspNetCore.SignalR</AssemblyName>
		<PackageId>Censeq.Framework.AspNetCore.SignalR</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.AspNetCore.SignalR" />
		<PackageReference Include="Volo.Abp.Caching" />
		<PackageReference Include="Volo.Abp.MultiTenancy" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Censeq.Framework.AspNetCore\Censeq.Framework.AspNetCore.csproj" />
	</ItemGroup>
</Project>
